### PR TITLE
Add some of the new/missing tracks

### PR DESCRIPTION
**Pull request by Krusen**
Adds the following tracks/configs:

- Belle Isle
- Charlotte Motor Speedway - Roval
- Tsukuba
  - 1000 Full
  - 1000 Full Reverse
  - 1000 Chicane
  - 1000 Outer
  - 2000 Full
  - 2000 Moto
  - 2000 Short
- Daytona 2007
  - Rallycross Short
  - Rallycross Long

### CODE REVIEW

**Comment by MorisatoK** [comment]
Awesome, thank you! I only just came back to iRacing very recently and haven't had the motivation to update the maps yet. I checked the maps and especially Charlotte seems to be not in synch with the actual car position. Could you have a look and fix that first before I merge?

**Comment by Krusen** [comment]
I did check most of them but did fiddle around with the SVG paths a bit afterwards, so might have messed something up :)

I'll recheck and push any updates.

Btw. the Daytona rally track maps doesn't seem to be 100% correct with the actual track, but they are copied from the website SVG, so I don't think it will get much better (without a lot of manual work).

**Comment by MorisatoK** [comment]
To make it as synch as possible I usually only fiddle with the start/finish point of the track. Just moving it a bit forward or backward should do the trick.

**Comment by Krusen** [comment]
Re-tested and adjusted all the tracks, they should be good now :)

I hadn't been thinking when testing earlier. I was mostly just verifying that the start/finish line was when I crossed the ingame start/finish line - which it obviously will always be...

**Comment by MorisatoK** [comment]
Thanks a lot, I will have a look at it this evening :)

> I hadn't been thinking when testing earlier. I was mostly just verifying that the start/finish line was when I crossed the ingame start/finish line - which it obviously will always be...

I know, I thought the same when beginning with the maps. :D 
Only when testing I learned that you actually have to look at the halfway mark of the track, because this will be the point that is visually the most apart from start/finish. If that position is in synch, basically everything else will also be in synch.

**Pull request merged**
